{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.namespace | quote }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key | quote }}: {{ $value | quote }}
  {{- end }}
{{- end }}